### ISSUE TITLE
Add external project to build vtkRenderingOpenXRRemoting

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerMixedReality#1]
Add the following external projects:

* [x] `External_OpenXR-SDK`: https://github.com/KhronosGroup/OpenXR-SDK
* [x] `External_vtkRenderingXR`
* [x] `External_vtkRenderingOpenXR`
* [x] `External_vtkRenderingOpenXRRemoting`
* [x] `External_OpenXRRemoting`

**Comment by adamrankin** [comment]
Linking this to KitwareMedical/SlicerVirtualReality#80

**Comment by jcfr** [comment]
The following external projects have been added in https://github.com/KitwareMedical/SlicerMixedReality/commit/f662c36704cb62a7f7177f7bee5be5ad0f31e1cb:

```
External_OpenXR-SDK
External_vtkRenderingXR
External_vtkRenderingOpenXR
External_vtkRenderingOpenXRRemoting
```
